config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :allocation_masters

  resources :allocations do
    collection do
      post "generate"
    end
  end
  
  resources :allocation_inputs
  resources :products
  resources :date_dims

end

app/models/allocation.rb
class Allocation < ActiveRecord::Base

	belongs_to :product
	has_one :allocation_input
	belongs_to :date_dim
	has_one :allocation_master

	scope :base_generated, -> { where(status: "base_generated")}

end

app/models/date_dim.rb
class DateDim < ActiveRecord::Base

	has_many :products
	has_many :allocation_inputs
	has_many :allocations
	has_many :invoices

end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
  before_action :set_allocation, only: [:show, :edit, :update, :destroy]

  # GET /allocations
  # GET /allocations.json
  def index
    @allocations = Allocation.all
  end

  def generate

    @ai = AllocationInput.where(:product_id => params[:product_ids], :allocation_basis => params[:allocation_basis])

    @ai.each do |ai|
      ai = Allocation.new(:product_id => ai.product_id, :allocation_input_id => ai.id, :allocation_units => ai.units, :allocation_date => ai.input_date, :date_dim_id => ai.date_dim_id, :allocation_name => params[:allocation_name], :status => "not_calculated")
      ai.save
    end

    a = Allocation.select(:date_dim_id, :allocation_units).where(:status => 'not_calculated').group(:date_dim_id).sum(:allocation_units)

    a.each do |k,v|
      my_alloc = Allocation.where(date_dim_id: k, :status => 'not_calculated')
      sum_units = Allocation.select(:allocation_units).where(date_dim_id: k, :status => "not_calculated").sum(:allocation_units)
      my_alloc.update_all(allocation_base: sum_units, status: 'base_generated')

      base = Allocation.base_generated

      base.each do |factor|
        factor.update_attributes(allocation_factor: (factor.allocation_units / factor.allocation_base), status: "calculated")
      end
    end
    
    redirect_to allocations_url
  
  end

  # GET /allocations/1
  # GET /allocations/1.json
  def show
  end

  # GET /allocations/new
  def new
    @allocation = Allocation.new
  end

  # GET /allocations/1/edit
  def edit
  end

  # POST /allocations
  # POST /allocations.json
  def create
    @allocation = Allocation.new(allocation_params)

    respond_to do |format|
      if @allocation.save
        format.html { redirect_to @allocation, notice: 'Allocation was successfully created.' }
        format.json { render :show, status: :created, location: @allocation }
      else
        format.html { render :new }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allocations/1
  # PATCH/PUT /allocations/1.json
  def update
    respond_to do |format|
      if @allocation.update(allocation_params)
        format.html { redirect_to @allocation, notice: 'Allocation was successfully updated.' }
        format.json { render :show, status: :ok, location: @allocation }
      else
        format.html { render :edit }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allocations/1
  # DELETE /allocations/1.json
  def destroy
    @allocation.destroy
    respond_to do |format|
      format.html { redirect_to allocations_url, notice: 'Allocation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allocation
      @allocation = Allocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allocation_params
      params.require(:allocation).permit(:allocation_master_id, :product_id, :allocation_input_id, :date_dim_id, :allocation_factor, :allocation_date, :allocation_name, :allocation_basis)
    end
end

app/helpers/allocations_helper.rb
module AllocationsHelper
end

app/views/allocations/_form.html.haml
= form_tag generate_allocations_path, method: :post do |f|
	- if @allocation.errors.any?
		#error_explanation
			%h2= "#{pluralize(@allocation.errors.count, "error")} prohibited this allocation from being saved:"
			%ul
				- @allocation.errors.full_messages.each do |msg|
					%li= msg

	.field
		- Product.all.each do |product|
			= check_box_tag "product_ids[]", product.id
			= product.name
			%br
		
		%br
		%br
		= select_tag "allocation_basis", options_for_select(AllocationInput.all.pluck(:allocation_basis).uniq)
		%br
		%br

		= "Name Your Allocation"
		= text_field_tag "allocation_name" 

		= submit_tag "Create Allocation"

app/views/allocations/edit.html.haml
%h1 Editing allocation

= render 'form'

= link_to 'Show', @allocation
\|
= link_to 'Back', allocations_path

app/views/allocations/generate.html.haml
hello

app/views/allocations/index.html.haml
%alloh1 Listing allocations

%table
  %thead
    %tr
      %th Allocation Name
      %th Status
      %th Product
      %th Date
      %th Allocation factor
      %th Allocation date
      %th Allocation Units
      %th Allocation base
      %t

  %tbody
    - @allocations.each do |allocation|
      %tr
        %td= allocation.allocation_name
        %td= allocation.status        
        %td= allocation.product.name
        %td= allocation.date_dim.input_date
        %td= allocation.allocation_factor
        %td= allocation.allocation_date
        %td= allocation.allocation_units
        %td= allocation.allocation_base
        %td= link_to 'Show', allocation
        %td= link_to 'Edit', edit_allocation_path(allocation)
        %td= link_to 'Destroy', allocation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Allocation', new_allocation_path

app/views/allocations/new.html.haml
%h1 New allocation

= render 'form'

= link_to 'Back', allocations_path

app/views/allocations/show.html.haml
%p#notice= notice

%p
  %b Allocation master:
  = @allocation.allocation_master_id
%p
  %b Product:
  = @allocation.product_id
%p
  %b Allocation input:
  = @allocation.allocation_input_id
%p
  %b Date dim:
  = @allocation.date_dim_id
%p
  %b Allocation factor:
  = @allocation.allocation_factor
%p
  %b Allocation date:
  = @allocation.allocation_date

= link_to 'Edit', edit_allocation_path(@allocation)
\|
= link_to 'Back', allocations_path