config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :allocation_masters

  resources :allocations do
    collection do
      post "generate"
    end
  end
  
  resources :allocation_inputs
  resources :products
  resources :date_dims

end

app/models/allocation_input.rb
class AllocationInput < ActiveRecord::Base

	belongs_to :date_dim
	belongs_to :product
	has_many :allocations

	after_save :assign_product_id, :assign_period, :assign_date_dim_id

	def assign_product_id
		p = Product.where("name = ?", self.product_name).first
		self.update_columns(:product_id => p.id)
	end

	def assign_period
		self.update_columns(:period => self.input_date.beginning_of_month)
	end

	def assign_date_dim_id
		d = DateDim.where("input_date = ?", self.period).first
		self.update_columns(:date_dim_id => d.id)
	end


end

app/controllers/allocation_inputs_controller.rb
class AllocationInputsController < ApplicationController
  before_action :set_allocation_input, only: [:show, :edit, :update, :destroy]

  # GET /allocation_inputs
  # GET /allocation_inputs.json
  def index
    @allocation_inputs = AllocationInput.all
  end

  # GET /allocation_inputs/1
  # GET /allocation_inputs/1.json
  def show
  end

  # GET /allocation_inputs/new
  def new
    @allocation_input = AllocationInput.new
  end

  # GET /allocation_inputs/1/edit
  def edit
  end

  # POST /allocation_inputs
  # POST /allocation_inputs.json
  def create
    @allocation_input = AllocationInput.new(allocation_input_params)

    respond_to do |format|
      if @allocation_input.save
        format.html { redirect_to @allocation_input, notice: 'Allocation input was successfully created.' }
        format.json { render :show, status: :created, location: @allocation_input }
      else
        format.html { render :new }
        format.json { render json: @allocation_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allocation_inputs/1
  # PATCH/PUT /allocation_inputs/1.json
  def update
    respond_to do |format|
      if @allocation_input.update(allocation_input_params)
        format.html { redirect_to @allocation_input, notice: 'Allocation input was successfully updated.' }
        format.json { render :show, status: :ok, location: @allocation_input }
      else
        format.html { render :edit }
        format.json { render json: @allocation_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allocation_inputs/1
  # DELETE /allocation_inputs/1.json
  def destroy
    @allocation_input.destroy
    respond_to do |format|
      format.html { redirect_to allocation_inputs_url, notice: 'Allocation input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allocation_input
      @allocation_input = AllocationInput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allocation_input_params
      params.require(:allocation_input).permit(:input_date, :product_name, :units, :allocation_basis, :date_dim_id, :product_id)
    end
end

app/helpers/allocation_inputs_helper.rb
module AllocationInputsHelper
end

app/views/allocation_inputs/_form.html.haml
= form_for @allocation_input do |f|
  - if @allocation_input.errors.any?
    #error_explanation
      %h2= "#{pluralize(@allocation_input.errors.count, "error")} prohibited this allocation_input from being saved:"
      %ul
        - @allocation_input.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :input_date
    = f.date_select :input_date
  .field
    = f.label :product_name
    = f.text_field :product_name
  .field
    = f.label :units
    = f.text_field :units
  .field
    = f.label :allocation_basis
    = f.text_field :allocation_basis
  .field
    = f.label :date_dim_id
    = f.number_field :date_dim_id
  .field
    = f.label :product_id
    = f.number_field :product_id
  .actions
    = f.submit 'Save'

app/views/allocation_inputs/edit.html.haml
%h1 Editing allocation_input

= render 'form'

= link_to 'Show', @allocation_input
\|
= link_to 'Back', allocation_inputs_path

app/views/allocation_inputs/index.html.haml
%h1 Listing allocation_inputs

%table
  %thead
    %tr
      %th Input date
      %th Product name
      %th Units
      %th Allocation basis
      %th Date dim
      %th Product
      %th
      %th
      %th

  %tbody
    - @allocation_inputs.each do |allocation_input|
      %tr
        %td= allocation_input.input_date
        %td= allocation_input.product_name
        %td= allocation_input.units
        %td= allocation_input.allocation_basis
        %td= allocation_input.date_dim_id
        %td= allocation_input.product_id
        %td= link_to 'Show', allocation_input
        %td= link_to 'Edit', edit_allocation_input_path(allocation_input)
        %td= link_to 'Destroy', allocation_input, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Allocation input', new_allocation_input_path

app/views/allocation_inputs/new.html.haml
%h1 New allocation_input

= render 'form'

= link_to 'Back', allocation_inputs_path

app/views/allocation_inputs/show.html.haml
%p#notice= notice

%p
  %b Input date:
  = @allocation_input.input_date
%p
  %b Product name:
  = @allocation_input.product_name
%p
  %b Units:
  = @allocation_input.units
%p
  %b Allocation basis:
  = @allocation_input.allocation_basis
%p
  %b Date dim:
  = @allocation_input.date_dim_id
%p
  %b Product:
  = @allocation_input.product_id

= link_to 'Edit', edit_allocation_input_path(@allocation_input)
\|
= link_to 'Back', allocation_inputs_path