config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :allocation_masters

  resources :allocations do
    collection do
      post "generate"
    end
  end
  
  resources :allocation_inputs
  resources :products
  resources :date_dims

end

app/models/allocation_master.rb
class AllocationMaster < ActiveRecord::Base

	has_many :allocations
	has_many :invoices

end

app/controllers/allocation_masters_controller.rb
class AllocationMastersController < ApplicationController
  before_action :set_allocation_master, only: [:show, :edit, :update, :destroy]

  # GET /allocation_masters
  # GET /allocation_masters.json
  def index
    @allocation_masters = AllocationMaster.all
  end

  # GET /allocation_masters/1
  # GET /allocation_masters/1.json
  def show
  end

  # GET /allocation_masters/new
  def new
    @allocation_master = AllocationMaster.new
  end

  # GET /allocation_masters/1/edit
  def edit
  end

  # POST /allocation_masters
  # POST /allocation_masters.json
  def create
    @allocation_master = AllocationMaster.new(allocation_master_params)

    respond_to do |format|
      if @allocation_master.save
        format.html { redirect_to @allocation_master, notice: 'Allocation master was successfully created.' }
        format.json { render :show, status: :created, location: @allocation_master }
      else
        format.html { render :new }
        format.json { render json: @allocation_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allocation_masters/1
  # PATCH/PUT /allocation_masters/1.json
  def update
    respond_to do |format|
      if @allocation_master.update(allocation_master_params)
        format.html { redirect_to @allocation_master, notice: 'Allocation master was successfully updated.' }
        format.json { render :show, status: :ok, location: @allocation_master }
      else
        format.html { render :edit }
        format.json { render json: @allocation_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allocation_masters/1
  # DELETE /allocation_masters/1.json
  def destroy
    @allocation_master.destroy
    respond_to do |format|
      format.html { redirect_to allocation_masters_url, notice: 'Allocation master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allocation_master
      @allocation_master = AllocationMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allocation_master_params
      params.require(:allocation_master).permit(:allocation_name, :allocation_input_id)
    end
end

app/helpers/allocation_masters_helper.rb
module AllocationMastersHelper
end

app/views/allocation_masters/_form.html.haml
= form_for @allocation_master do |f|
  - if @allocation_master.errors.any?
    #error_explanation
      %h2= "#{pluralize(@allocation_master.errors.count, "error")} prohibited this allocation_master from being saved:"
      %ul
        - @allocation_master.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :allocation_name
    = f.text_field :allocation_name
  .field
    = f.label :allocation_input_id
    = f.number_field :allocation_input_id
  .actions
    = f.submit 'Save'

app/views/allocation_masters/edit.html.haml
%h1 Editing allocation_master

= render 'form'

= link_to 'Show', @allocation_master
\|
= link_to 'Back', allocation_masters_path

app/views/allocation_masters/index.html.haml
%h1 Listing allocation_masters

%table
  %thead
    %tr
      %th Allocation name
      %th Allocation input
      %th
      %th
      %th

  %tbody
    - @allocation_masters.each do |allocation_master|
      %tr
        %td= allocation_master.allocation_name
        %td= allocation_master.allocation_input_id
        %td= link_to 'Show', allocation_master
        %td= link_to 'Edit', edit_allocation_master_path(allocation_master)
        %td= link_to 'Destroy', allocation_master, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Allocation master', new_allocation_master_path

app/views/allocation_masters/new.html.haml
%h1 New allocation_master

= render 'form'

= link_to 'Back', allocation_masters_path

app/views/allocation_masters/show.html.haml
%p#notice= notice

%p
  %b Allocation name:
  = @allocation_master.allocation_name
%p
  %b Allocation input:
  = @allocation_master.allocation_input_id

= link_to 'Edit', edit_allocation_master_path(@allocation_master)
\|
= link_to 'Back', allocation_masters_path